### ISSUE TITLE
Problem: How to avoid impossible to execute execution claims due to interface having insufficient balance?

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-dutchX#122]

**Comment by hilmarx** [comment]
Problem: In order to guarantee execution to users, interfaces require to have at least 0.5ETH balance on gelatoCore at execution time. It can happen, that interfaces after minting several claims, withdraw all their stake and leave their customers with not executable execution claims.

**Possible solutions:**

1) For each outstanding execution claim, interfaces are required to have a minimum balance of e.g. 0.1ETH on the core which they cannot withdraw. This however poses some risk for interfaces by having users that mint claims that will never get executed, leaving them with eth locked up on the core that they cannot withdraw. This could be counteracted by having an expirary date (e.g. 3 months) on every claim, after which the claim can be cancelled by the interface on core, not refunding the user (actually incentivizing users to mint claims that have a high probability of getting executed). For this to work, we would be required to implement another state variable in the core counting the outstanding execution claims of each interface, which will limit the amount of ETH the interface is able to withdraw & limiting the amount of new claims the interface can mint. Moreover each execution Claim requires an  additional call data variables representing the timestamp of the execution claim

2) Creating an executeWithoutReward() func at core, which enables users to execute the transaction by themselves #116. This has the downside of users being charged twice for one execution and actually just being forced to execute by themselves.

**Comment by hilmarx** [comment]
Problem continued:

The actual problem in this case is that in our current implementation, users have to trust the interface to a) precharge the correct amount over time / predict gas costs correctly plus 2) behave honestly by simply not withdrawing all the ETH when a lot of execution claims got minted.

Rather than simply basing that on trust and "over time people will only use trusted interfaces", we can add some incentives in gelatoCore that interfaces have to stake larger amounts of eth that cannot be withdrawn until all the users requirements are met. 

The true power of our idea comes from enabling all devs in the world to create their own unique trigger action pair that they can offer as an interface to users, however we need to design the system as such that they cannot fuck over the user too bad in terms of gas. In terms of what actually happens in the smart contract, it should be the communities role to curate **(curation markets)** these action/trigger pairs

**Comment by hilmarx** [comment]
=> Implement solution 1)

**Comment by gitpusha** [comment]
Luis Edits
------

I went for a slightly different approach that I think is more elegant:

- `GTAIs` need to `transfer ether` for each `minting` of an `executionClaim`

- this `msg.value` is added to their `gtaiBalance`

- `GTAIs` can only `withdraw` if they have `0` `executionClaims` outstanding

- `GTAIs` should code ways to `cancel` `bad executionClaims` into their `smart contracts`, so that they can reach a state of `0 executionClaims outstanding` , even if there are `bad executionClaims` (ones that can never be executed)

**Comment by gitpusha** [comment]
Open issue with the new design:
**Chained Execution Claim Minting** - the `GTAI` `deposits` `funds` into its `gtaiBalance` every time it `mints` another `chained` `executionClaim`

This could be seen as a further built-in `GTAI liquidity assurance measure` though --> discuss!

**Comment by gitpusha** [comment]
In the light of the **paying for chained executionClaims** I opened issue #145

**Comment by hilmarx** [comment]
The problem we are trying to address is that someone needs to overcollateralize on gelato core to assure executionClaims always get executed. We decided that this should be done by third parties, aggregators, to enable users to have certainty about the cost (the prepayment). 

Now I proposed to simply say that aggregators must keep a fixed stake (ETH) per outstanding execution claim on gelatoCore, which can only be withdrawn if the claim gets burned (through execution or cancellation). You now proposed that aggregators have to transfer a fixed amount of ETH for every mint and that they can only withdraw their ETH if they have 0 outstanding ETH on gelatoCore. 

Your implementation seems to be more restrive, as it forces aggregators to always send eth, rather than giving them the freedom to choose how they overcollateralize by themselves. They could still send some eth every time they mint a token by us adding an ``` if(msg.value > 0 ) ``` statement at the beginning of the mint func. However, I don't see the reason for making that a requirement. Aggregator should be free to send 10ETH once at the beginning and then being able to mint a lot of tokens for their customers without the need to send ether every single time. 

This also has the advantage of not locking away all of the interfaces' balance until every executionClaim is executed, but a fraction of it based on the minimum balance amount per executionClaim defined by us.

This still seems far from perfect, but I still like it better than having to send ether every time and having ones total balance locked up until the last executionClaim gets burned. 

Your version probably has only one extra state read in the mint() func (when mine would check the no.of outstanding execution claims plus minBalancePerClaim, but provides aggregators with more flexibility for the amount that can be withdrawn. We should note that if we make it that restrictive for aggregators to withdraw their stake, they might not want to stake in the first place.

Regarding the cancellation of executionClaims, this has to be done on the action, because in the future with create2, we need the action to then take the money from the escrow contract and send it back to the owner's wallet. Hence in gelatoCore, ```cancel()``` should call something like 

```
bytes payload = abi.encodeWithSelector(_actionAddress.cancel.selector, _actionpayload)
_action.call(payload)
```

The expiration date can be passed as calldata and checked at the beginning of the ```cancel()``` func.

**Comment by gitpusha** [comment]
this is `deprecated` by the new design where `executors` run the `business model` and we operate under the `executors will take losses` assumption/model (us being executors anyhow) 

see https://github.com/gelatodigital/gelato/issues/1 for code base update
