### ISSUE TITLE
Hilmars review of Luis SC changes

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-dutchX#140]

**Comment by hilmarx** [comment]
**GTA.sol**

- do we need all these ```onlyGelatoCore``` modifiers? Is there any risk associated with other contracts calling these function? They dont have state after all. 

**GTA Chained Minting.sol**

- Possibility to modularize further by passing dappInterfaec as payload for sellOnDutchX action, so that not only our interface can interact with the action, but arbitrary interfaces could.
- getSelector func is the same for action / trigger.

**GelatoActionsStandard.sol**

- sufficientGas() => we already check on core that we only use the saved gas, dont see a need to check that again in the contract except for testing

**ActionDutchXSell.sol**

- see issue #141 regarding how we should modularize the checking of tokens on actions / conditions
- Re-entrancy protection is sufficient on core, no need in actions / triggers

**ActionWithdrawFromDutchXToBeneficiary.sol**

- I would keep it simple for now and not add the complexity to add a beneficiary to the user. Advanced users can potentially do it by minting a second claim that if token X is transferred to their address, automatically forwards the tokens to another wallet. Later feature
- ```_standardACtionChecks``` should be conducted before minting, not after
- no need for Re-entrancy protection, it will be handled on core
- I would rename the GelatoDutchXStandard and all associated contracts to gelatoDutchXInterface

**ActionChainedDutchXSellMintWithdraw.sol**

- have dappInterface in payload to make chained execution claim usable by multiple interfaces
- why do we need the ```super``` when calling the function? Shouldn't that be an internal function call as we inherent from the contract?
- Delete beneficiary 

**TriggerTimestampPassed.sol**

- lets only check func Selector at minting time in aggregator
- bit confusing that we use ```now``` in one func and ```block.timestamp``` in the other
- Let's have time trigger / actions under ```Ethereum Utilities```. We will later also add stuff like recevied tokens, ethere recevied, balance, and so on...

**TriggerDutchXAuctionCleared.sol**

- For each Trigger contract, we require two funcs that the User Interface will interact with. First is the actual condition (i.e. ```fired```) and the second is another view function returning the current value relevant for the user (e.g. in case of uniswap: Current Market price of ETH => DAI). Best case would be if these two funcs would always be named the same. The second view function should return something useful for the UI, like market price in uniswaps case of true or false in case of ```didTheAuctionEnd```

**IcedOut.sol**

- What's the purpose of the ```acceptEther``` func?
- We require two topUp funcs, one callable externally by the owner to top of the aggregator and passing ether from owner to core and a second one using the aggregators balance directly to top up on core

**Comment by hilmarx** [comment]
For the actions requiring us to pass the executionClaimOwner, see #142

**Comment by gitpusha** [comment]
**GTA.sol**

- I removed the modifiers and functions as we can handle the checks via `web3.js` in frontend
--> principle: the less solidity code, the better

**Comment by gitpusha** [comment]
This is somewhat `deprecated` - refer to https://github.com/gelatodigital/gelato/issues/1 for the most recent `codebase` update inside **new gelato repo**
