### ISSUE TITLE
Chained Execution Claims Problems: executionClaimMintingDeposit (gtai) and prepaidExecutionFee (user)

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato-dutchX#145]
1. GTAIs currently transfer an extra executionClaimMintingDeposit to their core balance for every chained executionClaim they mint - this means they end up `overcollaterlising` for every `chained claim` they `mint` - this could be seen as a feature though

2. If the minted chained executionClaim is another chainedExecutionClaim, then there is the possibility of an `infinite chained execution claim minting loop` - the `user` did not pay the `GTAI` for that - this seems to be rather a `bug` than a feature

3. We probably need to restrict the `minting` of `chained execution claims` in a way that there is a `hard cap` on the `length` of the `chain` - maybe something like max `2 linked executionclaims` would be the easiest.

Regarding point3: implementation suggestion:

- introduce `one time written to state` in `GelatoActionRegistry` standard that flags an `action` as `mintingAction` 

- read from `mintingActions` `state` inside GTAI's `activateChainedTA` function - revert if `chainedAction` is `flagged` as `mintingAction` 

Positive: we prevent the `minting loop funding problem`
Negative: we only have a possible `chain length` of `2`

The main crux of the problem seems to be the lack of `prepayment` from `users` at `initial minting time` - it is impossible to predict the `length` of a `conditional execution chain`. The problem of `GTAIs over-depositing` could probably be solved - but the former problem seems unsolvable.

**Comment by gitpusha** [comment]
related to issue #122

**Comment by hilmarx** [comment]
Aggregators have to whitelist actions that users can mint through them. These first execution claims can be chainedExecutionClaims, but how many chainedExecutionClaims will be minted at the end of the process should be known before minting the first one, because it is hardcoded in the contracts.

Therefore aggregators, based on my current understanding, can simply choose to never whitelist the first chainedExecutionClaim that will result in such an infinite loop. Am I missing something here?

**Comment by hilmarx** [comment]
> it is impossible to predict the length of a conditional execution chain

I don't get this part, based on the design I saw last week, it must always be known how many executionClaims can possibly be minted based on the chainedExecutionClaim. And as aggregators whitelist those claims, there should not be a problem. Need for clarification here.

**Comment by gitpusha** [comment]
closing this issue in favor of https://github.com/gelatodigital/gelato/issues/1
