### ISSUE TITLE
msgSender-safety

### ISSUE THREAD

**Issue by gitpusha** [gelatodigital/gelato-dutchX#151]
- [x] **the `user`/`executionClaimOwner` must be `msg.sender` on `gelatoCore.mintExecutionClaim()`**

- [x] the `user`/`executionClaimOwner` pays the `executor` directly (no more `gtai`s in between) - done via `userProxies`

- [x] `executors` have `prices` on `gelatoCore` that are factored into the `executionClaimMintingDeposit()` formula.

- [x] `userBalances` on `gelatoCore` - done via `userProxy balances`

- [x] the `user` must pay the `executionClaimMintingDeposit()` at `minting time` into their `userBalance` on `gelatoCore`

- [x] `frontends` pick an `executor` for the `user`. they can pick their `own executor node` to guarantee `execution uptime` or even to `run an execution service business` - no more address(0) default due to price ambiguity.

- [x]  `executors` are paid the `executionClaimMintingDeposit` the `user` `prepaid` from the `user`'s `userBalance` - done via `userProxies`

- [x] we assume that `executors` `run businesses` and also `execute` `for a loss` (due to higher than calculated for `gas prices`, if they `miscalculated` their `executorPrice` at `mintingTime`

**Comment by hilmarx** [comment]
like the to do list

**Comment by hilmarx** [comment]
- [ ] Users deploy one-time proxy wallets that manage their funds and which give special rights to core to conduct txs on its behalf

**Comment by gitpusha** [comment]
implemented in new design
